TRAIN:
  ENABLE: True
  DATASET: blip_fusion_rgb_dataset #blip_fusion_rgb_dataset # kinetics_sparse Blip_fusion_rgb_dataset
  BATCH_SIZE: 16
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: False
  CHECKPOINT_FILE_PATH: /vol/bitbucket/sna21/CUENet/best_checkpoints/baseline/best-001.pyth
DATA:
  USE_OFFSET_SAMPLING: True
  DECODING_BACKEND: decord
  NUM_FRAMES: 16 #64
  SAMPLING_RATE: 4 #16
  TRAIN_JITTER_SCALES: [384, 480]
  TRAIN_CROP_SIZE: 192  # Instead of 224
  TEST_CROP_SIZE: 256   # Instead of 336
  INPUT_CHANNEL_NUM: [3]
  PATH_TO_DATA_DIR: /vol/bitbucket/sna21/dataset/VioGuard
  PATH_PREFIX: /vol/bitbucket/sna21/dataset/VioGuard
  TRAIN_JITTER_SCALES_RELATIVE: [0.08, 1.0]
  TRAIN_JITTER_ASPECT_RELATIVE: [0.75, 1.3333]
  CAPTION_PATH_PREFIX: /vol/bitbucket/sna21/dataset/VioGuard/blip
  POSE_PATH_PREFIX: /vol/bitbucket/sna21/dataset/VioGuard/multi/pose_outputs
UNIFORMERV2:
  BACKBONE: 'uniformerv2_l14_336'
  N_LAYERS: 4
  N_DIM: 1024
  N_HEAD: 16
  MLP_FACTOR: 4.0
  BACKBONE_DROP_PATH_RATE: 0.
  DROP_PATH_RATE: 0.
  MLP_DROPOUT: [0.5, 0.5, 0.5, 0.5]
  CLS_DROPOUT: 0.5
  RETURN_LIST: [20, 21, 22, 23]
  NO_LMHRA: True
  TEMPORAL_DOWNSAMPLE: False
  DELETE_SPECIAL_HEAD: True
MODEL:
  NUM_CLASSES: 2
  ARCH: uniformerv2
  MODEL_NAME: BlipFusionRGBCUENet_v2 #BlipFusionRGBCUENet_v2 #Uniformerv2 FusionCUENet ImprovedFusionCUENet BlipFusionCUENet BlipFusionRGBCUENet
  LOSS_FUNC: crd_loss #dynamic_ce_tloss #cross_entropy #dynamic_ce_tloss
  DROPOUT_RATE: 0.5
  USE_CHECKPOINT: True
  CHECKPOINT_NUM: [24]
  FREEZE_TEXT_ENCODER: True
  USE_RGB: True
  USE_POSE: True
  USE_TEXT: False
  POSE_USE_VELOCITY: True
TEST:
  ENABLE: False
  DATASET: blip_fusion_rgb_dataset #blip_fusion_rgb_dataset # fusion_dataset kinetics_sparse Fusion_blip_dataset
  BATCH_SIZE: 1
  NUM_SPATIAL_CROPS: 1
  NUM_ENSEMBLE_VIEWS: 1
  CHECKPOINT_FILE_PATH: /vol/bitbucket/sna21/CUENet/best_checkpoints/cvpr_rlv/checkpoint_epoch_00179.pyth
  
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: /vol/bitbucket/sna21/checkpoints/eccv_distillation_try/
